---
title: General Purpose Images
description: Quick overview of the main differences between general-purpose SUSE Linux Base Container Images.
slug: general-purpose-bci
---

The general-purpose container images include a minimum set of packages
to keep their size small. You can use it as a starting point for building
other container images or for deploying specific software using the free BCI
repository.

A complete list of images is available
https://registry.suse.com/repositories?sort=featured&categories%5B%5D=bci[here].

== Base and Init—When you need flexibility

These images come with a package manager (Zypper and RPM) and the free SUSE
Linux BCI repository. Allowing you to install software available in the
repository and customize the image. The downside is the size of the image.
These are the largest images, which may not be the best choice for a production
deployment.

The key difference between BCI Base and BCI Init is that the latter comes with
systemd preinstalled.

== Minimal—When you do not need Zypper

This is a stripped-down version of BCI Base. BCI Minimal comes with the RPM
package manager but not Zypper. This reduces the image size considerably.
However, while RPM can install and remove packages, it lacks support for
repositories and automated dependency resolution.

Use this image for creating deployment containers that include all desired
packages. While it is possible to install packages, it requires manual
download and resolution. For this reason, this approach is not recommended, as
it is prone to errors.

== Micro—When you need a small image

This image has fewer preinstalled packages and no package managers. It is ideal
for deploying binaries compiled externally or in a previous stage.

We recommend using BCI Micro as the final stage to deploy a project.

== BusyBox—When you need the smallest and GPLv3-free image

This image includes only the most basic tools provided by the BusyBox project.
Reducing the size even further compared to BCI Micro. Furthermore, the image
contains no GPLv3-licensed software.

When using BusyBox tools, keep in mind that they differ from GNU Coreutils.
Scripts written for Bash or GNU Coreutils may require modification.

== FIPS—When you need validated, encrypted modules

BCI Base and BCI Micro are also offered with FIPS mode enabled. However, it does
not include any certified binaries. Images with certified binaries are available
through a subscription.

Use these images in deployment scenarios that require FIPS 140-2 or FIPS 140-3.

== Approximate image size

For your reference, below are the approximate sizes of each image. Keep in mind
that the provided numbers are rough estimations.

* SUSE Linux BCI Base ~100-120 MB
* SUSE Linux BCI Base FIPS ~150-175 MB
* SUSE Linux BCI Init ~140-150 MB
* SUSE Linux BCI Minimal ~35-45 MB
* SUSE Linux BCI Micro ~25 MB
* SUSE Linux BCI Micro FIPS ~36 MB
* SUSE Linux BCI BusyBox ~15 MB

